//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Create_GasCard
    {
        public string GasCardName { get; set; }
        public string GasCardNum { get; set; }
        public string GasCardPin { get; set; }
        public string StatusName { get; set; }
    }
}
