//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DriverGroups = new HashSet<DriverGroup>();
            this.SignOuts = new HashSet<SignOut>();
            this.TransportationRequests = new HashSet<TransportationRequest>();
            this.TransportationRequests1 = new HashSet<TransportationRequest>();
        }
    
        public int UserId { get; set; }
        public string BannerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public int StatusId { get; set; }
        public string OfficeAreaCode { get; set; }
        public string OfficePhoneNumber { get; set; }
        public string CellAreaCode { get; set; }
        public string CellPhoneNumber { get; set; }
        public Nullable<bool> ApprovedDmv { get; set; }
        public string Email { get; set; }
        public string SupervisorEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverGroup> DriverGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignOut> SignOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationRequest> TransportationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationRequest> TransportationRequests1 { get; set; }
        public virtual UserStatus UserStatus { get; set; }
    }
}
