//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Create_Vehicle
    {
        public string VehiclePlate { get; set; }
        public string VehicleName { get; set; }
        public string StatusName { get; set; }
        public string CampusCode { get; set; }
    }
}
