
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Transportation
{

using System;
    using System.Collections.Generic;
    
public partial class TransporationRequest
{

    public int TransReqID { get; set; }

    public int UserID { get; set; }

    public string OfficeNumber { get; set; }

    public string CellPhoneNumber { get; set; }

    public int VehicleId { get; set; }

    public int VehicleAddonId { get; set; }

    public bool NeedGasCard { get; set; }

    public System.DateTime LeaveDate { get; set; }

    public System.TimeSpan LeaveTime { get; set; }

    public System.DateTime ReturnDate { get; set; }

    public System.TimeSpan ReturnTime { get; set; }

    public string TripPurpose { get; set; }

    public int NumOfStudents { get; set; }

    public Nullable<int> PassengerGroupId { get; set; }

    public bool Approved { get; set; }

    public Nullable<int> ProcessedUserId { get; set; }



    public virtual User User { get; set; }

    public virtual VehicleAddon VehicleAddon { get; set; }

    public virtual Vehicle Vehicle { get; set; }

}

}
