//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Transportation_Log
    {
        public string BannerId { get; set; }
        public string Destination { get; set; }
        public string VehicleName { get; set; }
        public string GasCardName { get; set; }
        public string KeyName { get; set; }
    }
}
