//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public string VehiclePlate { get; set; }
        public string VehicleName { get; set; }
        public int StatusId { get; set; }
        public int CampusId { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
    }
}
