//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationRequest_View
    {
        public long RId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BannerId { get; set; }
        public string Email { get; set; }
        public string OfficePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string DepartmentName { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.TimeSpan> LeaveTime { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.TimeSpan> ReturnTime { get; set; }
        public string TripPurpose { get; set; }
        public Nullable<int> NumOfStudents { get; set; }
    }
}
