//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationRequest
    {
        public int TransReqId { get; set; }
        public int RequesterUserId { get; set; }
        public Nullable<int> DriverGroupId { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public System.TimeSpan LeaveTime { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public System.TimeSpan ReturnTime { get; set; }
        public string Destination { get; set; }
        public string TripPurpose { get; set; }
        public int NumOfStudents { get; set; }
        public Nullable<int> PassengerGroupId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> ProcessedUserId { get; set; }
    
        public virtual TransportationRequest TransportationRequests1 { get; set; }
        public virtual TransportationRequest TransportationRequest1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
