//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.SignOuts = new HashSet<SignOut>();
            this.TransportationRequests = new HashSet<TransportationRequest>();
        }
    
        public int VehicleId { get; set; }
        public string VehiclePlate { get; set; }
        public string VehicleName { get; set; }
        public int StatusId { get; set; }
        public int CampusId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> VehicleAddonId { get; set; }
    
        public virtual Campus Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignOut> SignOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationRequest> TransportationRequests { get; set; }
        public virtual VehicleAddon VehicleAddon { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
