//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilitiesCheckOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Department_Key { get; set; }
        public string DEPARTMENTID { get; set; }
        public string DEPARTMENT1 { get; set; }
    }
}
