//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilitiesCheckOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int Key_ID { get; set; }
        public string Key_Name { get; set; }
        public int Vehicle_ID { get; set; }
        public bool Key_Checked_Out { get; set; }
    }
}
