//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilitiesCheckOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleLog
    {
        public int VehicleLogID { get; set; }
        public int UserID { get; set; }
        public int DeptID { get; set; }
        public string Destination { get; set; }
        public int VehID { get; set; }
        public int KeyID { get; set; }
        public int StaffID { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
    }
}
