//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilitiesCheckOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleLog
    {
        public int VehicleLogId { get; set; }
        public int UserId { get; set; }
        public int DeptId { get; set; }
        public string Destination { get; set; }
        public int VehId { get; set; }
        public int KeyId { get; set; }
        public int StaffId { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
    }
}
